### ISSUE TITLE
Broken by Update v1.01 [Shadow Warrior 3]

### ISSUE THREAD

**Issue by brunoanc** [DaZombieKiller/UE4Console#1]
The console can't be opened anymore on Shadow Warrior 3 after today's v1.01 update.

**Comment by brunoanc** [comment]
It seems that they've removed the pdb file, which i believe was necessary for this to work :(

**Comment by DaZombieKiller** [comment]
Yeah, if they've removed the PDB file then this will no longer work. You'll need to either downgrade the game or hope that Universal UE4 Unlocker eventually supports the game.
